DT_A    = 'dawntrail_a'
DT_S    = 'dawntrail_s'
EW_A    = 'endwalker_a'
EW_S    = 'endwalker_s'
SHB_A   = 'shadowbringers_a'
SHB_S   = 'shadowbringers_s'
SB_A    = 'stormblood_a'
SB_S    = 'stormblood_s'
HW_A    = 'heavensward_a'
HW_S    = 'heavensward_s'
ARR_A   = 'a_realm_reborn_a'
ARR_S   = 'a_realm_reborn_s'
FATE    = 'rare_fates'
TRAINS  = 'trains'

HUNT_SUBSCRIPTIONS = ('dt_a', 'dt_s', 'ew_a', 'ew_s', 'shb_a', 'shb_s', 'sb_a', 'sb_s', 'hw_a', 'hw_s', 'arr_a', 'arr_s')
